

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for login
-- ----------------------------
DROP TABLE IF EXISTS `login`;
CREATE TABLE `login`  (
  `id` int(11) NULL DEFAULT NULL,
  `username` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `email` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `password` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `repass` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `ho` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `ten` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `active` int(11) NULL DEFAULT NULL,
  `level` int(11) NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of login
-- ----------------------------
INSERT INTO `login` VALUES (1, 'loi', '133', '123', '123', 'le', 'loi', 1, NULL);
INSERT INTO `login` VALUES (17, 'fhsqf', 'nghia.nguyen1622@gmail.com', '1234', '1234', 'dsga', 'asd', 1, NULL);
INSERT INTO `login` VALUES (18, 'sfdsf', 'nghia.nguyen1622@gmail.com', '1234', '1234', 'qwe', 'sadfaf', 1, NULL);
INSERT INTO `login` VALUES (19, 'fasd', 'nghia.nguyen1622@gmail.com', '1234', '1234', 'nghiaw', 'sadfaf', 1, NULL);

-- ----------------------------
-- Table structure for producttype
-- ----------------------------
DROP TABLE IF EXISTS `producttype`;
CREATE TABLE `producttype`  (
  `id` int(11) NULL DEFAULT NULL,
  `name` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `active` int(11) NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of producttype
-- ----------------------------
INSERT INTO `producttype` VALUES (1, 'Iphone', 1);
INSERT INTO `producttype` VALUES (2, 'Samsung', 1);
INSERT INTO `producttype` VALUES (3, 'Vsmart', 1);

-- ----------------------------
-- Table structure for sanpham
-- ----------------------------
DROP TABLE IF EXISTS `sanpham`;
CREATE TABLE `sanpham`  (
  `id` int(11) NULL DEFAULT NULL,
  `name` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `price` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `type` int(11) NULL DEFAULT NULL,
  `quatily` int(11) NULL DEFAULT NULL,
  `lower` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `img` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `des` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `active` int(11) NULL DEFAULT NULL,
  `pricea` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `mausac` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `mausaca` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `tinhtrang` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `manhinh` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `hedieuhanh` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `camerasau` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `cameratruoc` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `cpu` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `ram` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `bonhotrong` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `thesim` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `dungluongpin` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `imgdd` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `mota` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `tinhnang` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `noidung` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `imgdemo` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `noidunga` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `imgdemoa` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `noidungb` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `imgdemob` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `dungluong` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `dungluonga` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of sanpham
-- ----------------------------
INSERT INTO `sanpham` VALUES (1, 'Điện thoại iPhone 11 Pro Max 64GB', '30490000', 1, 30, '30', 'images/iphone/1.jpg', 'Điện thoại iPhone 11 Pro Max 64GB', 1, '33990000', 'Đen', 'Trắng', 'Còn hàng', 'OLED, 6.5\", Super Retina XDR', ' iOS 13', ' 3 camera 12 MP', ' 12 MP\n', ' Apple A13 Bionic 6 nhân', ' 4 GB', '64 GB\n', '1 eSIM & 1 Nano SIM, Hỗtrợ4G', '3969 mAh, có sạc nhanh', 'images/iphone/dd/1.jpg', 'Trong năm 2019 thì chiếc smartphone được nhiều người mong muốn sở hữu trên tay và sử dụng nhất không ai khác chính là iPhone 11 Pro Max 64GB tới từ nhà Apple.', 'Camera được cải tiến mạnh mẽ\nKiểu dáng đơn giản, tiện lợi di chuyển\n', 'Chắc chắn lý do lớn nhất mà bạn muốn nâng cấp lên iPhone 11 Pro Max chính là cụm camera mới được Apple nâng cấp rất nhiều.', 'images/iphone/demo/1.jpg', 'Lần đầu tiên chúng ta sẽ có một chiếc iPhone với 3 camera ở mặt sau và cả 3 camera này đều có độ phân giải là 12 MP.\n\n', 'images/iphone/demoa/1.jpg', 'Chúng ta sẽ có một camera góc thường, một camera góc rộng và một camera tele đáp ứng đầy đủ nhu cầu chụp ảnh hàng ngày của người dùng.\n\n', 'images/iphone/demob/1.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (2, 'Điện thoại iPhone 11 Pro Max 512GB\n', '39990000', 1, 30, '30', 'images/iphone/2.jpg', 'Điện thoại iPhone 11 Pro Max 512GB\n', 1, '41990000', 'Đen', 'Trắng', 'Còn hàng', ' OLED, 6.5\", Super Retina XDR', ' iOS 13', '3 camera 12 MP', ' 12 MP', ' Apple A13 Bionic 6 nhân', ' 4 GB', '512 GB', '1 eSIM & 1 Nano SIM, Hỗtrợ4G', '3969 mAh, có sạc nhanh', 'images/iphone/dd/2.jpg', 'Để tìm kiếm một chiếc smartphone có hiệu năng mạnh mẽ và có thể sử dụng mượt mà trong 2-3 năm tới thì không có chiếc máy nào xứng đang hơn chiếc iPhone 11 Pro Max 512GB mới ra mắt trong năm 2019 của Apple.', 'Hiệu năng \"đè bẹp\" mọi đối thủ', 'iPhone 11 Pro Max 512GB năm nay sử dụng chip Apple A13 Bionic mới nhất, nhanh và tiết kiệm điện hơn so với A12 năm ngoái.', 'images/iphone/demo/2.jpg', 'Máy cũng sở hữu riêng một con chip AI Neural Engine sẽ phụ trách các tính năng xử lý hình ảnh như Deep Fusion và Night Mode.', 'images/iphone/demoa/2.jpg', 'Theo Apple thì đây là điện thoại thông minh có hiệu suất nhanh nhất thế giới ở thời điểm ra mắt.', 'images/iphone/demob/2.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (3, 'Điện thoại iPhone 11 Pro Max 256GB', '36490000', 1, 30, '30', 'images/iphone/3.jpg', 'Điện thoại iPhone 11 Pro Max 256GB', 1, '37990000', 'Đen', 'Trắng', 'Còn hàng', 'OLED, 6.5\", Super Retina XDR', ' iOS 13', '3 camera 12 MP', ' 12 MP', ' Apple A13 Bionic 6 nhân', ' 4 GB', '256 GB', '1 eSIM & 1 Nano SIM, Hỗtrợ4G', '3969 mAh, có sạc nhanh', 'images/iphone/dd/3.jpg', 'iPhone 11 Pro Max 256GB là chiếc iPhone cao cấp nhất trong bộ 3 iPhone Apple giới thiệu trong năm 2019 và quả thực chiếc smartphone này mang trong mình nhiều trang bị xứng đáng với tên gọi \"Pro\".', 'Pro về camera sau', 'Camera là một trong những điểm nâng cấp mạnh mẽ nhất năm nay Apple mang đến cho chiếc iPhone 11 Pro Max.', 'images/iphone/demo/3.jpg', 'Đó là lần đầu tiên một chiếc iPhone sở hữu tới 3 camera ở mặt sau với 3 tiêu cự khác nhau mà người ta vẫn gọi là \"từ nhà tới trường\" đáp ứng mọi nhu cầu nhiếp ảnh của người dùng.', 'images/iphone/demoa/3.jpg', 'Ngoài một camera góc rộng và một camera tele vốn dĩ đã xuất hiện từ thời iPhone 7 Plus thì năm nay iPhone 11 Pro Max được trang bị thêm một ống kính góc siêu rộng nữa.', 'images/iphone/demob/3.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (4, 'Điện thoại iPhone 11 Pro 256GB', '32490000', 1, 30, '30', 'images/iphone/4.jpg', 'Điện thoại iPhone 11 Pro 256GB', 1, '34990000', 'Đen', 'Trắng', 'Còn hàng', ' OLED, 5.8\", Super Retina XDR', ' iOS 13', '3 camera 12 MP', ' 12 MP', ' Apple A13 Bionic 6 nhân', ' 4 GB', '256 GB', '1 eSIM & 1 Nano SIM, Hỗtrợ4G', '3969 mAh, có sạc nhanh', 'images/iphone/dd/4.jpg', 'iPhone 11 Pro 256GB có lẽ sẽ là chiếc iPhone được nhiều người dùng lựa chọn khi nó sở hữu mức giá tốt hơn chiếc iPhone 11 Pro Max nhưng vẫn sở hữu tất cả những ưu điểm trên người anh em của mình.', 'Camera chính là điểm nhấn', 'Trong sự kiện giới thiệu bộ 3 iPhone mới thì Apple dành rất nhiều thời gian để nói về camera và quả thật bộ 3 camera trên iPhone 11 Pro mới thực sự rất ấn tượng.', 'images/iphone/demo/4.jpg', 'Thay vì chỉ có 2 camera thì năm nay chúng ta đã được bổ sung thêm 1 camera góc siêu rộng rất đáng giá.', 'images/iphone/demoa/4.jpg', 'Thêm 1 camera người dùng sẽ có thêm nhiều tính năng, thêm nhiều lựa chọn để có được bức ảnh đẹp nhất đăng lên facebook khoe với bạn bè.', 'images/iphone/demob/4.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (5, 'Điện thoại iPhone 11 Pro Max 64GB', '30490000', 1, 30, '30', 'images/iphone/5.jpg', 'Điện thoại iPhone 11 Pro Max 64GB', 1, '33990000', 'Đen', 'Trắng', 'Còn hàng', 'OLED, 6.5\", Super Retina XDR', ' iOS 13', '3 camera 12 MP', ' 12 MP', ' Apple A13 Bionic 6 nhân', ' 4 GB', '64 GB', '1 eSIM & 1 Nano SIM, Hỗtrợ4G', '3969 mAh, có sạc nhanh', 'images/iphone/dd/5.jpg', 'Trong năm 2019 thì chiếc smartphone được nhiều người mong muốn sở hữu trên tay và sử dụng nhất không ai khác chính là iPhone 11 Pro Max 64GB tới từ nhà Apple.', 'Camera được cải tiến mạnh mẽ', 'Chắc chắn lý do lớn nhất mà bạn muốn nâng cấp lên iPhone 11 Pro Max chính là cụm camera mới được Apple nâng cấp rất nhiều.', 'images/iphone/demo/5.jpg', 'Lần đầu tiên chúng ta sẽ có một chiếc iPhone với 3 camera ở mặt sau và cả 3 camera này đều có độ phân giải là 12 MP.', 'images/iphone/demoa/5.jpg', 'Chúng ta sẽ có một camera góc thường, một camera góc rộng và một camera tele đáp ứng đầy đủ nhu cầu chụp ảnh hàng ngày của người dùng.', 'images/iphone/demob/5.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (6, 'Điện thoại iPhone 11 Pro 64GB', '28490000', 1, 30, '30', 'images/iphone/6.jpg', 'Điện thoại iPhone 11 Pro 64GB', 1, '30990000', 'Đen', 'Trắng', 'Còn hàng', ' OLED, 5.8\", Super Retina XDR', ' iOS 13', '3 camera 12 MP', ' 12 MP', ' Apple A13 Bionic 6 nhân', ' 4 GB', '64 GB', '1 eSIM & 1 Nano SIM, Hỗtrợ4G', '3969 mAh, có sạc nhanh', 'images/iphone/dd/6.jpg', 'Nếu như bây giờ để lựa chọn một thiết bị có thể sử dụng ổn định và được cập nhật trong khoảng 3 năm nữa thì không có sự lựa chọn nào xuất sắc hơn chiếc iPhone 11 Pro 64GB, siêu phẩm mới được giới thiệu cách đây không lâu tới từ Apple.', 'Khi hiệu năng vượt qua mọi giới hạn', 'iPhone vốn nổi tiếng với sự mượt mà và ổn định, điều đó lại một lần nữa được Apple khẳng định với chiếc iPhone 11 Pro.', 'images/iphone/demo/6.jpg', 'Chiếc iPhone này được nâng cấp lên con chip Apple A13 Bionic mới nhất mang lại cho bạn sức mạnh mà theo Apple là vượt xa những chiếc flagship Android có mặt trên thị trường hiện nay.', 'images/iphone/demoa/6.jpg', 'Với 4 GB RAM và 64 GB bộ nhớ trong thì máy tự tin có thể chơi mọi tựa game dù có đồ họa khủng tới đâu đi nữa đang có mặt trên Apple Store.', 'images/iphone/demob/6.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (7, 'Điện thoại iPhone Xs Max 256GB', '25990000', 1, 30, '30', 'images/iphone/7.jpg', 'Điện thoại iPhone Xs Max 256GB', 1, '30990000', 'Đen', 'Trắng', 'Còn hàng', 'OLED, 6.5\", Super Retina XDR', ' iOS 13', ' Chính 12 MP & Phụ 12 MP', '7 MP', ' Apple A12 Bionic 6 nhân', ' 4 GB', '256 GB', '1 eSIM & 1 Nano SIM, Hỗtrợ4G', '3174 mAh, có sạc nhanh', 'images/iphone/dd/7.jpg', 'Sau 1 năm mong chờ, chiếc smartphone cao cấp nhất của Apple đã chính thức ra mắt mang tên iPhone Xs Max 256 GB. Máy các trang bị các tính năng cao cấp nhất từ chip A12 Bionic, dàn loa đa chiều cho tới camera kép tích hợp trí tuệ nhân tạo.', 'Hiệu năng đỉnh cao cùng chip Apple A12', 'iPhone Xs Max được Apple trang bị cho con chip mới toanh hàng đầu của hãng mang tên Apple A12.', 'images/iphone/demo/7.jpg', 'Hơn nữa, chiếc điện thoại iPhone còn có bộ xử lý đồ họa mạnh mẽ được Apple thiết kế riêng giúp hiệu năng được cải thiện rất lớn về mặt đồ họa của máy.', 'images/iphone/demoa/7.jpg', 'Chưa dừng lại ở đó, máy còn được tích hợp trí thông minh nhân tạo giúp phần cứng tối ưu hiệu suất, nhờ đó mà các thao tác của bạn được xử lý một cách nhanh chóng hơn.', 'images/iphone/demob/7.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (8, 'Điện thoại iPhone 11 256GB\n', '24490000', 1, 30, '30', 'images/iphone/8.jpg', 'Điện thoại iPhone 11 256GB\n', 1, '25990000', 'Đen', 'Trắng', 'Còn hàng', ' IPS LCD, 6.1\", Liquid Retina', ' iOS 13', ' Chính 12 MP & Phụ 12 MP', ' 12 MP', ' Apple A13 Bionic 6 nhân', ' 4 GB', '256 GB', '1 eSIM & 1 Nano SIM, Hỗtrợ4G', '3110 mAh, có sạc nhanh', 'images/iphone/dd/8.jpg', 'iPhone 11 256GB là chiếc máy có mức giá \"dễ chịu\" trong bộ 3 iPhone vừa được Apple giới thiệu và nếu bạn muốn được trải nghiệm những nâng cấp về camera mới hay hiệu năng hàng đầu mà lại không muốn bỏ ra quá nhiều tiền thì đây thực sự là lựa chọn hàng đầu ', 'Hiệu năng vẫn tương đương phiên bản Pro Max', 'Mặc dù có mức giá rẻ hơn nhưng không vì vậy mà iPhone 11 bị cắt giảm đi về mặt cấu hình.', 'images/iphone/demo/8.jpg', 'Máy vẫn sẽ sở hữu cho mình con chip Apple A13 Bionic mạnh mẽ cùng 4 GB RAM tương đương với người anh em đắt tiền iPhone 11 Pro Max.', 'images/iphone/demoa/8.jpg', 'Phiên bản này sẽ có bộ nhớ lên tới 256 GB thoải mái cho bạn cài đặt game ứng dụng hay lưu trữ video độ phân giải cao.', 'images/iphone/demob/8.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (9, 'Điện thoại iPhone 11 64GB', '20990000', 1, 30, '30', 'images/iphone/9.jpg', 'Điện thoại iPhone 11 64GB', 1, '20990000', 'Đen', 'Trắng', 'Còn hàng', ' IPS LCD, 6.1\", Liquid Retina', ' iOS 13', ' Chính 12 MP & Phụ 12 MP', ' 12 MP', ' Apple A13 Bionic 6 nhân', ' 4 GB', '64 GB', '1 eSIM & 1 Nano SIM, Hỗtrợ4G', '3110 mAh, có sạc nhanh', 'images/iphone/dd/9.jpg', 'Sau bao nhiêu chờ đợi cũng như đồn đoán thì cuối cùng Apple đã chính thức giới thiệu bộ 3 siêu phẩm iPhone 11 mạnh mẽ nhất của mình vào tháng 9/2019. Có mức giá rẻ nhất nhưng vẫn được nâng cấp mạnh mẽ như chiếc iPhone Xr năm ngoái, đó chính là phiên bản i', 'Nâng cấp mạnh mẽ về camera', 'Nói về nâng cấp thì camera chính là điểm có nhiều cải tiến nhất trên thế hệ iPhone mới.', 'images/iphone/demo/9.jpg', 'Nếu như trước đây iPhone Xr chỉ có một camera thì nay với iPhone 11 chúng ta sẽ có tới hai camera ở mặt sau.', 'images/iphone/demoa/9.jpg', 'Ngoài camera chính vẫn có độ phân giải 12 MP thì chúng ta sẽ có thêm một camera góc siêu rộng và cũng với độ phân giải tương tự.', 'images/iphone/demob/9.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (10, 'Điện thoại Samsung Galaxy A31', '5450000', 2, 30, '30', 'images/samsung/1.jpg', 'Điện thoại Samsung Galaxy A31', 1, '6490000', 'Đen', 'Trắng', 'Còn hàng', 'Super AMOLED, 6.4\", Full HD+', 'Android 10', ' Chính 48 MP & Phụ 8 MP, 5 MP, 5 MP', '20 MP', ' MediaTek MT6768 8 nhân (Helio P65)', '6 GB', '128 GB', '1 Nano SIM, Hỗ trợ 4G', ' 5000 mAh, có sạc nhanh', 'images/samsung/dd/1.jpg', 'Galaxy A31 là mẫu smartphone tầm trung mới ra mắt đầu năm 2020 của Samsung. Thiết bị gây ấn tượng mạnh với ngoại hình thời trang, cụm 4 camera đa chức năng, vân tay dưới màn hình và viên pin khủng lên đến 5000 mAh.', 'Thiết kế đặc trưng của dòng Galaxy A 2020', 'Tổng thể thiết kế của Galaxy A31 mang nhiều nét tương đồng với hai người anh em Galaxy A31 và A71. Mặt lưng của thiết bị vẫn được tạo điểm nhấn với cụm camera lớn và các vân kim cương đẹp mắt.', 'images/samsung/demo/1.jpg', 'Ở mặt trước, Samsung trang bị cho A31 màn hình tràn viền Infinity-U với kích thước 6.4 inch, sử dụng tấm nền Super AMOLED với độ phân giải Full HD+ cho hình ảnh sắc nét và tươi sáng.', 'images/samsung/demoa/1.jpg', 'Viền màn hình được làm mỏng ở các cạnh bên và cạnh trên, tuy nhiên phần “cằm” máy vẫn khá dày chứ không được làm thanh thoát như trên các mẫu máy cao cấp hơn.', 'images/samsung/demob/1.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (11, 'Điện thoại Samsung Galaxy A51 (8GB/128GB)', '8390000', 2, 30, '30', 'images/samsung/2.jpg', 'Điện thoại Samsung Galaxy A51 (8GB/128GB)', 1, NULL, 'Đen', 'Trắng', 'Còn hàng', 'Super AMOLED, 6.4\", Full HD+', 'Android 11', ' Chính 48 MP & Phụ 8 MP, 5 MP, 5 MP', '32 MP', ' Exynos 9611 8 nhân', ' 8 GB', '129 GB', '2 Nano SIM, Hỗ trợ 4G', '4000 mAh, có sạc nhanh', 'images/samsung/dd/2.jpg', 'Galaxy A51 8GB là phiên bản nâng cấp RAM của smartphone tầm trung đình đám Galaxy A51 từ Samsung. Sản phẩm nổi bật với thiết kế sang trọng, màn hình Infinity-O cùng cụm 4 camera đột phá. sản phẩm cũng là Smartphone Android Bán Chạy Nhất Thế Giới Quý 1/202', 'Màn hình tràn viền Infinity-O thời thượng', 'Mặt trước của Galaxy A51 8GB nổi bật với màn hình tràn viền vô cực Infinity-O kế thừa từ series S, Note cao cấp. ', 'images/samsung/demo/2.jpg', 'Phần đục lỗ rất nhỏ gọn, tạo độ thoáng cho màn hình, mình thực sự rất thích thiết kế này vì nó đẹp hơn tai thỏ, giọt nước, trong khi lại bền hơn cơ chế “thò thụt” của camera dạng pop-up.', 'images/samsung/demoa/2.jpg', 'Cảm biến vân tay dưới màn hình cũng được Samsung trang bị lên máy, cho tốc độ mở khóa nhanh chóng, đem tới sự tiện lợi cao nhất cho người dùng khi cho phép nhận diện chính xác ngay cả khi tay có hơi ướt.', 'images/samsung/demob/2.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (12, 'Điện thoại Samsung Galaxy Z Flip', '36000000', 2, 30, '30', 'images/samsung/3.jpg', 'Điện thoại Samsung Galaxy Z Flip', 1, NULL, 'Đen', 'Trắng', 'Còn hàng', 'Chính: Dynamic AMOLED, phụ: Super AMOLED, 6.7\", Quad HD (2K)', ' Android 10', 'Chính 12 MP & Phụ 12 MP', '10 MP', ' Snapdragon 855+ 8 nhân', ' 8 GB', '256 GB', '1 eSIM & 1 Nano SIM, Hỗ trợ 4G', ' 3300 mAh, có sạc nhanh', 'images/samsung/dd/3.jpg', 'Cuối cùng sau bao nhiêu thời gian chờ đợi, chiếc điện thoại Samsung Galaxy Z Flip đã được Samsung ra mắt tại sự kiện Unpacked 2020. Siêu phẩm với thiết kế màn hình gập vỏ sò độc đáo, hiệu năng tuyệt đỉnh cùng nhiều công nghệ thời thượng, dẫn dầu 2020.', 'Đột phá với thiết kế màn hình gập', 'Samsung Galaxy Z Flip được thiết kế với kiểu dáng màn hình gập lấy ý tưởng từ dòng sản phẩm Galaxy Fold từng gây nhiều tiếng vang trong năm 2019.', 'images/samsung/demo/3.jpg', 'Tuy nhiên điểm khác biệt là màn hình của Z Flip được thiết kế gập theo chiều dọc, khiến cho tổng thể máy có thể nằm gọn trong lòng bàn tay của người dùng như một phụ kiện thời trang cao cấp.', 'images/samsung/demoa/3.jpg', 'Bản lề của máy cũng có khả năng gập - mở với nhiều góc độ khác nhau, khi thiết bị ở trạng thái mở một nửa, màn hình sẽ tự động chia thành hai màn hình 4 inch vừa đủ để bạn có thể dễ dàng xem hình ảnh, nội dung hoặc video ở nửa trên của màn hình và thao t', 'images/samsung/demob/3.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (13, 'Điện thoại Samsung Galaxy A80', '8990000', 2, 30, '30', 'images/samsung/4.jpg', 'Điện thoại Samsung Galaxy A80', 1, '14990000', 'Đen', 'Trắng', 'Còn hàng', ' Super AMOLED, 6.7\", Full HD+', ' Android 9.0 (Pie)', 'Chính 48 MP & Phụ 8 MP, TOF 3D', ' Chính 48 MP & Phụ 8 MP, TOF 3D', ' Snapdragon 730 8 nhân', ' 8 GB', '128 GB', '2 Nano SIM, Hỗ trợ 4G', ' 3700 mAh, có sạc nhanh', 'images/samsung/dd/4.jpg', 'Samsung Galaxy A80 là chiếc smartphone mang trong mình rất nhiều đột phá của Samsung và hứa hẹn sẽ là \"ngọn cờ đầu\" cho những chiếc smartphone sở hữu một màn hình tràn viền thật sự.', 'Camera vừa trượt vừa xoay đầu tiên trên thế giới', 'Thực tế thì xu hướng màn hình tràn viền đã bắt đầu cách đây khá lâu nhưng có rất ít các hãng có thể mang một màn hình tràn viền đúng nghĩa lên chiếc smartphone của mình.', 'images/samsung/demo/4.jpg', 'Và Samsung Galaxy A80 là một hướng đi mới của Samsung về việc làm smartphone tràn viền khi hãng bố trí cụm camera chính (cũng chính là camera selfie) có thể vừa xoay vừa trượt.', 'images/samsung/demoa/4.jpg', 'Cụm camera trên máy sẽ tự động trượt lên đồng thời sở hữu một cơ chế xoay giúp nó xoay 180 độ về phía trước những lúc người dùng cần tới camera selfie.', 'images/samsung/demob/4.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (14, 'Điện thoại Samsung Galaxy S10 Lite', '12990000', 2, 30, '30', 'images/samsung/5.jpg', 'Điện thoại Samsung Galaxy S10 Lite', 1, '14990000', 'Đen', 'Trắng', 'Còn hàng', ' Super AMOLED, 6.7\", Full HD+', ' Android 10', 'Chính 48 MP & Phụ 12 MP, 5 MP', ' 32 MP', ' Snapdragon 855 8 nhân', ' 8 GB', ' 128 GB', '\n2 SIM Nano (SIM 2 chung khe thẻ nhớ), Hỗ trợ 4G', ' 4500 mAh, có sạc nhanh', 'images/samsung/dd/5.jpg', 'Samsung Galaxy S10 Lite là một phiên bản khác của dòng Galaxy S10 đã ra mắt trước đó nhưng mang trong mình khá nhiều khác biệt về ngoại hình cũng như bên trong.', 'Ngoại hình nổi bật dễ nhận biết', 'Mặc dù có tên gọi là S10 Lite nhưng ngoại hình của chiếc máy này mang khá nhiều thay đổi so với dòng S10 trước đó. Đầu tiên bạn sẽ dễ nhận thấy là trên màn hình Infinity-O thì camera selfie được đặt ở chính giữa thay vì lệch về góc trái như trên S10.', 'images/samsung/demo/5.jpg', 'Quay ra ở mặt sau thì bạn cũng dễ dàng nhận ra chiếc Galaxy S10 Lite với cụm camera to bản được làm hình chữ nhật trông rất hầm hố.', 'images/samsung/demoa/5.jpg', 'Khung viền được hoàn thiện từ chất liệu kim loại đem lại cảm giác cầm nắm chắc chắn và sang trọng.', 'images/samsung/demob/5.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (15, 'Điện thoại Samsung Galaxy Note 10 Lite', '9990000', 2, 30, '30', 'images/samsung/6.jpg', 'Điện thoại Samsung Galaxy Note 10 Lite', 1, '11490000', 'Đen', 'Trắng', 'Còn hàng', ' Super AMOLED, 6.7\", Full HD+', ' Android 10', 'Chính 12 MP & Phụ 12 MP, 12 MP', ' 32 MP', ' Exynos 9810 8 nhân', ' 8 GB', ' 128 GB', '\n2 SIM Nano (SIM 2 chung khe thẻ nhớ), Hỗ trợ 4G', ' 4500 mAh, có sạc nhanh', 'images/samsung/dd/6.jpg', 'Sau bao đồn đoán và trông ngóng thì cuối cùng \"người em út\" trong series Note 10 cũng đã chính thức trình làng với tên gọi Samsung Galaxy Note 10 Lite với những thay đổi nhất định về ngoại hình.', 'Ngoại hình mới mẻ theo xu thế', 'Samsung Galaxy Note 10 Lite nhìn chung vẫn sở hữu thiết kế quen thuộc của dòng Note 10 series ở mặt trước với rất ít viền xung quanh, các góc được bo tròn, một camera selfie nằm trong lỗ đục chính giữa.', 'images/samsung/demo/6.jpg', 'Tuy nhiên điểm khác biệt sẽ tới từ mặt lưng thay vì cụm camera đặt dọc như những phiên bản trước thì Samsung đã làm hình chữ nhật trông thu hút và hầm hố hơn.', 'images/samsung/demoa/6.jpg', 'Máy cũng sẽ không còn kiểu thiết kế cong ở 2 cạnh của màn hình mà thay vào đó là thiết kế phẳng tương tự như các sản phẩm cận cao cấp khác. Nhưng không vì đó mà kém phần sang trọng nhờ mặt kính bóng bẩy và màu sắc hút mắt người nhìn.', 'images/samsung/demob/6.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (16, 'Điện thoại Samsung Galaxy A71', '8390000', 2, 30, '30', 'images/samsung/7.jpg', 'Điện thoại Samsung Galaxy A71', 1, '10490000', 'Đen', 'Trắng', 'Còn hàng', ' Super AMOLED, 6.7\", Full HD+', ' Android 10', 'Chính 64 MP & Phụ 12 MP, 5 MP, 5 MP', '32 MP', ' Snapdragon 730 8 nhân', ' 8 GB', ' 128 GB', '\n2 SIM Nano (SIM 2 chung khe thẻ nhớ), Hỗ trợ 4G', ' 4500 mAh, có sạc nhanh', 'images/samsung/dd/7.jpg', 'Sau A51, Samsung tiếp tục ra mắt Galaxy A71 là đại diện kế tiếp thuộc thế hệ smartphone Galaxy A 2020. Máy được cải tiến với camera macro siêu cận đột phá, camera chính lên đến 64 MP cùng thiết kế thời thượng và cao cấp.', 'Màn hình lớn, trải nghiệm tràn viền cực đã', 'Galaxy A71 sở hữu màn hình tràn viền Infinity-O với rãnh camera được đặt chính giữa tương tự như trên flagship Note 10. Điểm cộng là phần rãnh camera nay đã được làm rất nhỏ, ít gây chú ý, cho trải nghiệm hình ảnh thoải mái và ít bị phân tâm hơn.\n\n', 'images/samsung/demo/7.jpg', 'Kích thước màn hình lên đến 6.7 inch, được \"phóng lớn\" so với Galaxy A51 (6.5 inch), cho không gian trải nghiệm thoải mái và đã mắt.', 'images/samsung/demoa/7.jpg', 'Tấm nền Super AMOLED độ phân giải Full HD+ mang lại độ tương phản tốt, màu đen sâu và hình ảnh được tái hiện rực rỡ, nịnh mắt hơn.', 'images/samsung/demob/7.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (17, 'Điện thoại Samsung Galaxy A70', '8290000', 2, 30, '30', 'images/samsung/8.jpg', 'Điện thoại Samsung Galaxy A70', 1, '9290000', 'Đen', 'Trắng', 'Còn hàng', ' Super AMOLED, 6.7\", Full HD+', ' Android 9.0 (Pie)', ' Chính 32 MP & Phụ 8 MP, 5 MP', '32 MP', ' Snapdragon 675 8 nhân', '6 GB', ' 128 GB', '\n2 SIM Nano (SIM 2 chung khe thẻ nhớ), Hỗ trợ 4G', ' 4500 mAh, có sạc nhanh', 'images/samsung/dd/8.jpg', 'Samsung Galaxy A70 là một phiên bản phóng to của chiếc Samsung Galaxy A50 đã ra mắt trước đó với nhiều cải tiến tới từ bên trong.', 'Màn hình kích thước lớn, trải nghiệm \"đã hơn\"', 'Màn hình của chiếc Galaxy A70 có kích thước khá lớn lên đến 6.7 inch độ phân giải Full HD+ trên tấm nền Super AMOLED.', 'images/samsung/demo/8.jpg', 'Các cạnh viền bezel được tinh chỉnh mỏng hơn, điều này giúp máy trông gọn gàng và cân xứng hơn rất nhiều.', 'images/samsung/demoa/8.jpg', 'Samsung vẫn trang bị cho Galaxy A70 một mặt lưng vẫn bằng nhựa, nhưng sử dụng chất liệu cao cấp hơn mà Samsung gọi là “3D Graffitistic”.', 'images/samsung/demob/8.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (18, 'Điện thoại Samsung Galaxy S10 Lite', '12990000', 2, 30, '30', 'images/samsung/9.jpg', 'Điện thoại Samsung Galaxy S10 Lite', 1, '14990000', 'Đen', 'Trắng', 'Còn hàng', ' Super AMOLED, 6.7\", Full HD+', 'Android 10', 'Chính 48 MP & Phụ 12 MP, 5 MP', '32 MP', 'Snapdragon 855 8 nhân', ' 8 GB', ' 128 GB', '\n2 SIM Nano (SIM 2 chung khe thẻ nhớ), Hỗ trợ 4G', ' 4500 mAh, có sạc nhanh', 'images/samsung/dd/9.jpg', 'Samsung Galaxy S10 Lite là một phiên bản khác của dòng Galaxy S10 đã ra mắt trước đó nhưng mang trong mình khá nhiều khác biệt về ngoại hình cũng như bên trong.', 'Ngoại hình nổi bật dễ nhận biết', 'Mặc dù có tên gọi là S10 Lite nhưng ngoại hình của chiếc máy này mang khá nhiều thay đổi so với dòng S10 trước đó. Đầu tiên bạn sẽ dễ nhận thấy là trên màn hình Infinity-O thì camera selfie được đặt ở chính giữa thay vì lệch về góc trái như trên S10.', 'images/samsung/demo/9.jpg', 'Quay ra ở mặt sau thì bạn cũng dễ dàng nhận ra chiếc Galaxy S10 Lite với cụm camera to bản được làm hình chữ nhật trông rất hầm hố.', 'images/samsung/demoa/9.jpg', 'Khung viền được hoàn thiện từ chất liệu kim loại đem lại cảm giác cầm nắm chắc chắn và sang trọng.', 'images/samsung/demob/9.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (19, 'Điện thoại Vsmart Star 3', '1840000', 3, 30, '30', 'images/vsmart/1.jpg', 'Điện thoại Vsmart Star 3', 1, '1990000', 'Đen', 'Trắng', 'Còn hàng', ' IPS LCD, 6.09\", HD+', ' Android 9.0 (Pie)', 'Chính 8 MP & Phụ 5 MP', '8 MP', ' Snapdragon 215 4 nhân', ' 2 GB', '16 GB', '\n2 Nano SIM, Hỗ trợ 4G', '3500 mAh', 'images/vsmart/dd/1.jpg', 'Chiếc điện thoại Vsmart Star 3 nổi bật với thiết kế giọt nước tràn viền, camera kép ở mặt lưng đi kèm mức giá bán vô cùng phải chăng cho người dùng Việt.', 'Nổi bật camera kép ở mặt lưng', 'Chiếc điện thoại Vsmart Star 3 được trang bị bộ đôi camera kép ở mặt lưng bao gồm một camera chính độ phân giải 8 MP và một camera góc siêu rộng 5 MP.', 'images/vsmart/demo/1.jpg', 'Camera của máy được hỗ trợ đầy đủ các tính năng chụp ảnh góc rộng, xóa phông, HDR, Panorama,... kết hợp cùng thuật toán hỗ trợ chụp chân dung mà không cần tới camera tele đáp ứng tốt nhu cầu chụp ảnh hằng ngày.', 'images/vsmart/demoa/1.jpg', 'Camera selfie của chiếc điện thoại Vsmart này có độ phân giải 8 MP hỗ trợ bằng công nghệ AI hứa hẹn sẽ mang đến cho người dùng những bức ảnh selfie tuyệt vời.', 'images/vsmart/demob/1.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (20, 'Điện thoại Vsmart Active 3 (6GB/64GB)', '3990000', 3, 30, '30', 'images/vsmart/2.jpg', 'Điện thoại Vsmart Active 3 (6GB/64GB)', 1, NULL, 'Đen', 'Trắng', 'Còn hàng', ' AMOLED, 6.39\", Full HD+', ' Android 9.0 (Pie)', 'Chính 48 MP & Phụ 8 MP, 2 MP', '16 MP', 'MediaTek Helio P60 8 nhân', '6 GB', ' 64 GB', '\n2 Nano SIM, Hỗ trợ 4G', '4020 mAh, có sạc nhanh', 'images/vsmart/dd/2.jpg', 'Ra mắt vào đầu năm 2020, Vsmart Active 3 (4GB/64GB) là một smartphone có hiệu năng ổn định, thời lượng pin cả ngày dài và còn nhiều tính năng đặc biệt khác nữa, hứa hẹn sẽ mang đến cho bạn một thiết bị công nghệ chẳng những thời trang còn rất hiện đại.', 'Sang trọng với mặt lưng kính, hiệu ứng gradient thời thượng', 'Mặt sau của Active 3 gồm 4 sự lựa chọn thời trang: Xanh lục bảo, Xanh sapphire, Đen thạch anh và Tím ngọc lấy cảm hứng từ vẻ đẹp của đá quý. Thiết kế cong nhẹ về hai cạnh và 4 góc được bo tròn mềm mại, Active 3 được hoàn thiện theo xu hướng gradient – bó', 'images/vsmart/demo/2.jpg', 'Cảm biến vân tay được tích hợp ở mặt lưng, dễ dàng được kích hoạt với độ bảo mật cao, tiện lợi khi sử dụng một tay.', 'images/vsmart/demoa/2.jpg', 'Vsmart Active 3 sở hữu màn hình tràn viền 6.39 inch với phần viền siêu mỏng, chiếm đến 92% tỉ lệ mặt trước máy, mang đến không gian sử dụng cực thoải mái. Tấm nền AMOLED cho hình ảnh sống động và tươi sáng, nịnh mắt hơn.', 'images/vsmart/demob/2.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (21, 'Điện thoại Vsmart Joy 3 (4GB/64GB)', '2990000', 3, 30, '30', 'images/vsmart/3.jpg', 'Điện thoại Vsmart Joy 3 (4GB/64GB)', 1, '3290000', 'Đen', 'Trắng', 'Còn hàng', ' IPS LCD, 6.5\", HD+', ' Android 9.0 (Pie)', 'Chính 13 MP & Phụ 8 MP, 2 MP', ' 8 MP', ' Snapdragon 632 8 nhân', ' 4 GB', ' 64 GB', '\n2 Nano SIM, Hỗ trợ 4G', '5000 mAh, có sạc nhanh', 'images/vsmart/dd/3.jpg', 'Vsmart Joy 3 4GB/64GB là một phiên bản mới, được nâng cấp nhẹ về RAM và bộ nhớ trong so với 2 mẫu smartphone cùng tên trước đó, mang đến thêm một sự lựa chọn hấp dẫn ở phân khúc giá rẻ cho người dùng.', 'Cấu hình nâng cấp với mức giá bình dân', 'Không vì mức giá rẻ mà cấu hình bị thua thiệt, Joy 3 bản 4GB vẫn được hãng Vsmart tích hợp vi xử lý tầm trung Snapdragon 632 cho hiệu năng xử lý mượt các tác vụ hàng ngày cũng như chiến tốt các tựa game hot nhất hiện nay như Liên Quân hay PUBG Mobile ở m', 'images/vsmart/demo/3.jpg', 'Tham khảo thêm: Tìm hiểu chip Qualcomm Snapdragon 632.', 'images/vsmart/demoa/3.jpg', 'Trong tầm giá này, hiếm có một smartphone nào được trang bị RAM 4GB như Vsmart Joy 3. Với dụng lượng RAM này, sẽ giúp máy xử lý đa nhiệm tốt hơn, hạn chế tình trạng bị treo hay load lại ứng dụng thường xuyên.', 'images/vsmart/demob/3.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (22, 'Điện thoại Vsmart Joy 3 (3GB/32GB)', '2690000', 3, 30, '30', 'images/vsmart/4.jpg', 'Điện thoại Vsmart Joy 3 (3GB/32GB)', 1, NULL, 'Đen', 'Trắng', 'Còn hàng', ' IPS LCD, 6.5\", HD+', ' Android 9.0 (Pie)', ' Chính 13 MP & Phụ 8 MP, 2 MP', ' 8 MP', ' Snapdragon 632 8 nhân', ' 3 GB', ' 32 GB', '\n2 Nano SIM, Hỗ trợ 4G', ' 5000 mAh, có sạc nhanh', 'images/vsmart/dd/4.jpg', 'Chiếc điện thoại Vsmart Joy 3 3GB/32GB mang trong mình thiết kế trẻ trung, hiện đại, hiệu năng tốt cùng thời lượng pin lớn với giá bán hấp dẫn phù hợp với đại đa số người dùng. Đây sẽ là chiếc điện thoại gây nhiều chú ý nhất trong thời gian sắp tới.', 'Thiết kế hiện đại, thời trang', 'Với thiết kế mặt lưng chuyển màu sắc độc đáo ôm khít thân máy, các góc cạnh được bo tròn mềm mại giúp Vsmart Joy 3 nằm gọn trong lòng bàn tay bạn.', 'images/vsmart/demo/4.jpg', 'Màn hình của máy có kích thước 6.5 inch sử dụng tấm nền IPS có màu sắc tốt cùng độ tương phản cao mang đến nội dung chi tiết, hình ảnh sắc nét tuyệt vời.', 'images/vsmart/demoa/4.jpg', 'Mang trong mình vi xử lý Snapdragon 632 giúp máy có thể đáp ứng tốt nhu cầu giải trí từ cơ bản như xem phim lướt web hằng ngày hay có thể chơi được các tựa game nhẹ.', 'images/vsmart/demob/4.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (23, 'Điện thoại Vsmart Star 4 (3GB/32GB)\n', '2490000', 3, 30, '30', 'images/vsmart/5.jpg', 'Điện thoại Vsmart Star 4 (3GB/32GB)', 1, NULL, 'Đen', 'Trắng', 'Còn hàng', ' IPS LCD, 6.09\", HD+', ' Android 10', ' Chính 8 MP & Phụ 5 MP', ' 8 MP', ' MediaTek Helio P35 8 nhân', ' 3 GB', '32 GB', '\n2 Nano SIM, Hỗ trợ 4G', '3500 mAh', 'images/vsmart/dd/5.jpg', 'Không kèn không trống, Vsmart một lần nữa khiến người dùng không khỏi bất ngờ khi tung ra Vsmart Star 4 một bản nâng cấp đáng kể về hiệu năng so với đàn anh Vsmart Star 3, dần khẳng định vị thế sản phẩm Việt trước các đối thủ khác trong tầm giá.', 'Màu sắc trẻ trung, thiết kế hợp xu hướng', 'Vsmart Star 4 trang bị màn hình viền mỏng, độ phân giải HD+ sắc nét mọi góc nhìn với tấm nền IPS LCD, nâng cao trải nghiệm hình ảnh cho người dùng khi xem phim, lướt web, chơi game,…', 'images/vsmart/demo/5.jpg', 'Thiết kế nguyên khối bên cạnh mặt kính cong 2.5D, cho cảm giác liền mạch, không cấn tay, chất lượng mặt lưng bằng nhựa cũng là một điểm cộng khi giúp máy có trọng lượng rất nhẹ, bám chắc tay, không bị mỏi sau quá trình dài sử dụng.', 'images/vsmart/demoa/5.jpg', 'Mặt lưng được nhà sản xuất ưu ái thiết kế với đường nét đẹp mắt, bo cong hai cạnh bên của máy, kết hợp với viền kim loại trên cảm biến vân tay, cho cảm giác sang trọng và tinh tế hơn hẳn khi so sánh với các dòng điện thoại khác cùng tầm giá.', 'images/vsmart/demob/5.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (24, 'Điện thoại Vsmart Joy 3 (2GB/32GB)', '2290000', 3, 30, '30', 'images/vsmart/6.jpg', 'Điện thoại Vsmart Joy 3 (2GB/32GB)', 1, NULL, 'Đen', 'Trắng', 'Còn hàng', ' IPS LCD, 6.5\", HD+', ' Android 9.0 (Pie)', ' Chính 13 MP & Phụ 8 MP, 2 MP', ' 8 MP', ' Snapdragon 632 8 nhân', ' 2 GB', ' 32 GB', '\n2 Nano SIM, Hỗ trợ 4G', ' 5000 mAh, có sạc nhanh', 'images/vsmart/dd/6.jpg', 'Vsmart Joy 3 2GB/32GB là chiếc điện thoại thương hiệu Việt với thiết kế màn hình giọt nước, cụm camera ấn tượng, dung lượng pin khủng đi kèm mức giá bán cực kỳ bình dân.', 'Thiết kế sang trọng', 'Máy có thiết kế màn hình giọt nước tràn viền kết hợp với mặt lưng với các hiệu ứng chuyển đổi màu đặc sắc cho cảm giác hiện đại, nổi bật.', 'images/vsmart/demo/6.jpg', 'Viền màn hình máy được làm cong 2.5D các góc cạnh được bo cong nhẹ nhàng cho cảm giác cầm nắm gọn gàng, chắc chắn.', 'images/vsmart/demoa/6.jpg', 'Máy được trang bị bộ ba camera ở mặt sau bao gồm 1 camera chính 13 MP và 1 camera góc rộng 8 MP và cuối cùng là 1 camera hỗ trợ chụp chân dung xóa phông 2 MP.', 'images/vsmart/demob/6.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (25, 'Điện thoại Vsmart Star 4 (2GB/32GB)', '2190000', 3, 30, '30', 'images/vsmart/7.jpg', 'Điện thoại Vsmart Star 4 (2GB/32GB)', 1, NULL, 'Đen', 'Trắng', 'Còn hàng', ' IPS LCD, 6.09\", HD+', ' Android 10', 'Chính 8 MP & Phụ 5 MP', ' 8 MP', 'MediaTek Helio P35 8 nhân', ' 2 GB', ' 32 GB', '\n2 Nano SIM, Hỗ trợ 4G', ' 3500 mAh', 'images/vsmart/dd/7.jpg', 'Vsmart Star 4 (2GB/32GB) chính là smartphone thế hệ mới Vsmart muốn giới thiệu tới người dùng Việt. Đây là sản phẩm tiếp nối thành công của Vsmart Star 3 với nhiều nâng cấp đáng giá về cấu hình và hiệu năng giúp Vsmart tiếp tục khẳng định vị thế của mình ', 'Màn hình tràn viền kích thước lớn', 'Vsmart Star 4 có thiết kế không quá nhiều khác biệt so với người tiền nhiệm Star 3 với màn hình giọt nước tràn viền kích thước lớn 6.09 inch.', 'images/vsmart/demo/7.jpg', 'Màn hình này cung cấp độ phân giải HD+ sử dụng màn hình IPS LCD, tỷ lệ khung hình 19.5:9 cho góc nhìn tốt, độ sáng cao, dễ dàng thao tác. ', 'images/vsmart/demoa/7.jpg', 'Viền màn hình của máy cũng được nhà sản xuất Việt trau chuốt vát cong 2.5D tạo được sự liền mạch, trơn tru khi vuốt tay từ màn hình xuống các cạnh.', 'images/vsmart/demob/7.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (26, 'Điện thoại Vsmart Bee 3', '1440000', 3, 30, '30', 'images/vsmart/8.jpg', 'Điện thoại Vsmart Bee 3', 1, '1590000', 'Đen', 'Trắng', 'Còn hàng', ' IPS LCD, 6.0\", HD+', ' Android 9.0 (Pie)', '8 MP', ' 5 MP', ' MediaTek MT6739WW 4 nhân\n', ' 2 GB', '16 GB', '\n2 Nano SIM, Hỗ trợ 4G', '3000 mAh', 'images/vsmart/dd/8.jpg', 'Vsmart Bee 3 là một chiếc smartphone với mức giá siêu rẻ được ra đời để phục vụ người dùng. Máy sở hữu hiệu năng đủ dùng cùng camera chất lượng tốt, màn hình lớn thoải mái và hệ điều hành VOS được tối ưu dành riêng cho người Việt.', NULL, NULL, 'images/vsmart/demo/8.jpg', 'Màn hình lớn 6 inch mang đến không gian hiển thị rộng rãi. Các thông tin và hình ảnh trên màn hình rõ ràng dễ đọc với cả người lớn tuổi.', 'images/vsmart/demoa/8.jpg', 'Vsmart Bee 3 với độ phân giải 8 MP cho camera sau giúp hình ảnh sắc nét. Máy có khả năng tự động lấy nét nhanh đặc biệt là ở điều kiện đủ ánh sáng. Máy hỗ trợ quay phim với độ phân giải Full HD.', 'images/vsmart/demob/8.jpg', '64GB', '256GB');
INSERT INTO `sanpham` VALUES (27, 'Điện thoại Vsmart Bee', '990000', 3, 30, '30', 'images/vsmart/9.jpg', 'Điện thoại Vsmart Bee', 1, NULL, 'Đen', 'Trắng', 'Còn hàng', 'IPS LCD, 5.45\", HD+', ' Android 8.1 (Oreo)', ' 8 MP', ' 5 MP', ' MediaTek MT6739 4 nhân', ' 1 GB', '16 GB', '\n2 Nano SIM, Hỗ trợ 4G', ' 2500 mAh', 'images/vsmart/dd/9.jpg', 'Vsmart Bee là một chiếc smartphone với mức giá siêu rẻ nhắm tới đối tượng người dùng có thu nhập thấp, muốn sở hữu một thiết bị phải chăng để trải nghiệm Android có nhiều tính năng.', 'Thiết kế đơn giản, nhỏ gọn', 'Vsmart Bee sở hữu thiết kế không quá cầu kỳ với một thân hình khá nhỏ gọn và dễ cầm nắm.', 'images/vsmart/demo/9.jpg', 'Máy có màn hình kích thước 5.45 inch vừa đủ để người dùng có thể trải nghiệm thông tin giải trí đa phương tiện trên máy.', 'images/vsmart/demoa/9.jpg', 'Vsmart Bee sở hữu camera chính có độ phân giải 8 MP với giao diện chụp ảnh đơn giản, dễ dàng làm quen và sử dụng.', 'images/vsmart/demob/9.jpg', '64GB', '256GB');

-- ----------------------------
-- Table structure for slide
-- ----------------------------
DROP TABLE IF EXISTS `slide`;
CREATE TABLE `slide`  (
  `id` int(11) NULL DEFAULT NULL,
  `name` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `img` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `imgqq` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `des` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `noidungsl` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `date` date NULL DEFAULT NULL,
  `active` int(11) NULL DEFAULT NULL,
  `imgvd` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `video` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `noidung` varchar(254) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `ngaydang` date NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of slide
-- ----------------------------
INSERT INTO `slide` VALUES (1, 'a', '133', '14', 'q', 'Sắm Samsung Galaxy Ưu Đãi Đến 20%', '2020-07-08', 1, '', '1', 'Sắm Samsung Galaxy Ưu Đãi Đến 20%', '2020-07-08');
INSERT INTO `slide` VALUES (2, 'b', NULL, NULL, 'w', 'OPPO Reno3 Series Giảm Đến 3,5 Triệu', '2020-07-08', 1, NULL, '1', 'OPPO Reno3 Series Giảm Đến 3,5 Triệu', '2020-07-08');
INSERT INTO `slide` VALUES (3, 'c', NULL, NULL, 'e', 'Sắm Ngay iPhone<br>Giảm Đến 5 Triệu', '2020-07-08', 1, NULL, '1', 'Sắm Ngay iPhone<br>Giảm Đến 5 Triệu', '2020-07-08');
INSERT INTO `slide` VALUES (4, 'd', NULL, NULL, 'r', 'Vivo V19 | V19 Neo<br>Giảm Đến 400 Ngàn', '2020-07-08', 1, NULL, '1', 'Vivo V19 | V19 Neo<br>Giảm Đến 400 Ngàn', '2020-07-08');
INSERT INTO `slide` VALUES (5, 'e', NULL, NULL, 't', 'Vivo V19 | V19 Neo<br>Giảm Đến 400 Ngàn', '2020-07-08', 1, NULL, '1', 'Vivo V19 | V19 Neo<br>Giảm Đến 400 Ngàn', '2020-07-08');

-- ----------------------------
-- Table structure for taikhoan
-- ----------------------------
DROP TABLE IF EXISTS `taikhoan`;
CREATE TABLE `taikhoan`  (
  `maTaiKhoan` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `tenDangNhap` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `email` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `matKhau` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `quyenTruyCap` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `trangThai` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  PRIMARY KEY (`maTaiKhoan`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of taikhoan
-- ----------------------------
INSERT INTO `taikhoan` VALUES ('1', 'Phuong', '123', '123', '123', '123');
INSERT INTO `taikhoan` VALUES ('1595351194122', '123', 'dokimphuong@gmail.com', '123Phuong@', '1', '2');
INSERT INTO `taikhoan` VALUES ('1595351385501', '123', 'dokimphuong@gmail.com', 'dd06e1627ba39b72666e3d6743969575', '1', '2');
INSERT INTO `taikhoan` VALUES ('1595351632626', '123', 'dokimphuong@gmail.com', 'c1a0ac378b465713e4d079fc0f402ec6', '1', '2');
INSERT INTO `taikhoan` VALUES ('1595351879849', '123', 'dokimphuong@gmail.com', '44c29edb103a2872f519ad0c9a0fdaaa', '1', '2');
INSERT INTO `taikhoan` VALUES ('1595352021711', '123', 'abc@gmail.com', 'c4ca4238a0b923820dcc509a6f75849b', '1', '2');
INSERT INTO `taikhoan` VALUES ('1595352490075', '234', '234', 'd9d56ad1653d97f6d072ac854e6a9b18', '2', '1');
INSERT INTO `taikhoan` VALUES ('1595353234495', '789', 'dokimphuong@gmail.com', '2cb0829539ac7179253b9c94402a4b30', '2', '1');
INSERT INTO `taikhoan` VALUES ('1595353453349', '567', 'abc@gmail.com', 'c96f403d65d67dce04f7cc5f905742bc', '2', '1');
INSERT INTO `taikhoan` VALUES ('1595513644569', 'duytvt', 'duy2410@gmail.com', '7b940275fcbec70fce4d2e85fd5044fb', '2', '1');

SET FOREIGN_KEY_CHECKS = 1;
